{% set name = "pybase64" %}
{% set version = "1.0.0" %}
{% set sha256 = "71a729b10232b38cba001e621dbaa6dbba2302dc44a93706295f1ff760f40876" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pybase64=pybase64.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pybase64

about:
  home: https://github.com/mayeut/pybase64/
  license: BSD-2.0
  license_family: BSD
  summary: 'Fast Base64 encoding/decoding in Python'
  doc_url: https://github.com/mayeut/pybase64/
  dev_url: https://github.com/mayeut/pybase64/

extra:
  recipe-maintainers:
    - njzjz
