travis:
  secure:
    BINSTAR_TOKEN: GHuU3hg8dinXiKzRLb+vpg7UWvGYZy7C30w1/3eU7k61xm9bivTXA2S9u7Rgsl9a23/MmnNUz9MLbBUtvWnHupxpIbP0zbJdUNqlJyRjmBNU4el8eaPrX+C51kr5KYzPDyVXoNM3WsmEQS5dPlIG2PwehNFlT0Vvi08bN4fC8pRQwSgARJHdagNwHN1H0Ll/uRDdTZ0zxajBpFRkzfHwGg0pH3GEHxa4fiJInbBfa2nHvRbLp8qDDbri3ubhd5Wybd9+Yxj6T2NPapgWbABlmrPqtTmkmhwmoJfMYzElMqzKG52atGQwbm9JAsUPU1yQ8cvl57nd3iOpcpUvp0YGv1q1yzkiLq+QV65rKXmz3G9B0nAwD7XW5MXzZFVZJE8gKSImATOl/UNi1sAvJLT6UHA2HvI+RhdW6h/oo6YN9G9bgkB72qPuQPr0Jvbi6yfFzUN0nBmPdQOwqgpgFqd+HkwUodyJJw6OXN0dPmmqJv6H+K5rHatPgVm2ACpwn0uJpHj59JQyEHFYi75+XPBfubX8JOJ4UhEsrBoWQUbfxmWJ+sQ5E1MBCaXU/FRhB2AZpDJEK5EvtLoN3f/iP0/fBCcYSo8JO8FaDJo/sveUZPpw16lPTKh36XD9D8VP08AH06fAWgRQE79HDWKVPZcjPtMtyr6sz2W5yA35br8dwIk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
